name: Windows Workflow
on: workflow_dispatch
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  calc-numbers:
    runs-on: windows-latest
    steps:
      # Runs a single command using the runners shell
      - name: run it
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          $Nr1 = 20
          $Nr2 = 50

          $Ergebnis = $Nr1 + $Nr2

          $Ergebnis
